export const languages = [
  {
    name: 'Javascript',
    desc: 'JavaScript is a dynamic, high-level programming language primarily utilized for front-end web development. It enables interactive and dynamic features on websites, enhancing user experience.',
    link: '',
    img: '/logos/logo-javascript.svg',
  },
  {
    name: 'Typescript',
    desc: 'Typescript is a free and open-source high-level programming langauge developed at Microsoft. It is a syntactic superset of JavaScript which adds static typing.',
    link: 'https://www.typescriptlang.org/',
    img: '/logos/ts-logo-128.svg',
  },
  {
    name: 'C++',
    desc: 'C++ is a versatile programming language renowned for efficiency, commonly applied in system software, games, and performance-critical applications, supporting both procedural and object-oriented programming.',
    link: '',
    img: '/logos/c++.svg',
  },
  {
    name: 'Python',
    desc: "Python is a versatile, high-level programming language celebrated for its simplicity and readability. Widely used in web development, data science, and automation, Python's extensive libraries make it a go-to choice for various applications.",
    link: 'https://www.python.org/',
    img: '/logos/python-5.svg',
  },
];

export const frontend = [
  {
    name: 'Reactjs',
    desc: 'React is an efficient JavaScript library for building user interfaces, known for its component-based architecture and seamless updates, simplifying the creation of interactive and scalable UIs.',
    link: 'https://www.react.dev',
    img: '/logos/react-2.svg',
  },
  {
    name: 'React Native',
    desc: 'React Native is a framework for building cross-platform mobile applications using JavaScript and React, enabling native performance with a single codebase for iOS and Android.',
    link: 'https://reactnative.dev',
    img: '/logos/expo.svg',
  },
  {
    name: 'Nextjs',
    desc: 'React is an efficient JavaScript library for building user interfaces, known for its component-based architecture and seamless updates, simplifying the creation of interactive and scalable UIs.',
    link: 'https://www.nextjs.org',
    img: '/logos/next-js-white.svg',
  },
  {
    name: 'Tailwind CSS',
    desc: 'Tailwind CSS is a utility-first CSS framework that streamlines web development. By providing a set of pre-designed utility classes, Tailwind simplifies styling and allows for rapid and consistent UI development.',
    link: 'https://www.nextjs.org',
    img: '/logos/tailwind-css-2.svg',
  },
  {
    name: 'Shadcn',
    desc: 'Shadcn is a collection of re-usable components that you can copy and paste into your apps.',
    link: 'https://ui.shadcn.com/',
    img: '/logos/shadcn.jpeg',
  },
  {
    name: 'Redux & RTK',
    desc: 'Shadcn is a collection of re-usable components that you can copy and paste into your apps.',
    link: 'https://redux-toolkit.js.org/',
    img: '/logos/redux.svg',
  },
  {
    name: 'Zustand',
    desc: 'Shadcn is a collection of re-usable components that you can copy and paste into your apps.',
    link: 'https://zustand-demo.pmnd.rs/',
    img: '/logos/zustand.svg',
  },
  {
    name: 'Tanstack query',
    desc: 'Shadcn is a collection of re-usable components that you can copy and paste into your apps.',
    link: 'https://tanstack.com/query',
    img: '/logos/react-query.svg',
  },
  {
    name: 'Figma',
    desc: 'Figma is a collaborative interface design tool used for designing, prototyping, and building modern user experiences with real-time team collaboration.',
    link: 'https://www.figma.com',
    img: '/logos/figma.svg',
  },
];

export const backend = [
  {
    name: 'Nodejs',
    desc: 'Node.js is a JavaScript runtime environment that enables server-side development. Leveraging the V8 JavaScript engine, Node.js is renowned for its non-blocking, event-driven architecture, making it efficient for building scalable and real-time applications.',
    link: 'https://nodejs.org/en',
    img: '/logos/nodejs-1.svg',
  },
  {
    name: 'Expressjs',
    desc: 'Shadcn is a collection of re-usable components that you can copy and paste into your apps.',
    link: 'https://expressjs.com/',
    img: '/logos/expressjs-109.svg',
  },
  {
    name: 'Honojs',
    desc: 'Shadcn is a collection of re-usable components that you can copy and paste into your apps.',
    link: 'https://expressjs.com/',
    img: '/logos/hono.svg',
  },
  {
    name: 'Prisma',
    desc: 'Shadcn is a collection of re-usable components that you can copy and paste into your apps.',
    link: 'https://expressjs.com/',
    img: '/logos/prisma-white.svg',
  },
  {
    name: 'Postgresql',
    desc: 'Shadcn is a collection of re-usable components that you can copy and paste into your apps.',
    link: 'https://expressjs.com/',
    img: '/logos/postgresql.svg',
  },
  {
    name: 'MongoDB',
    desc: 'MongoDB is a flexible NoSQL database, storing data in BSON documents for versatility. Its document-oriented approach and scalability make it ideal for diverse applications, simplifying development and handling large datasets efficiently.',
    link: 'https://www.mongodb.com/',
    img: '/logos/mongodb-icon-2.svg',
  },
  {
    name: 'AWS',
    desc: 'Amazon Web Services (AWS) is a cloud computing platform offering scalable infrastructure, including compute (EC2), storage (S3), and deployment services for modern applications.',
    link: 'https://aws.amazon.com',
    img: '/logos/aws.svg',
  },
  {
    name: 'Cloudflare Workers',
    desc: 'Shadcn is a collection of re-usable components that you can copy and paste into your apps.',
    link: 'https://expressjs.com/',
    img: '/logos/cloudflare-workers.svg',
  },
  {
    name: 'Socket.IO',
    desc: 'Socket.IO enables real-time, bidirectional communication between clients and servers, commonly used for live updates, chats, and event-driven applications.',
    link: 'https://socket.io',
    img: '/logos/socket-io.svg',
  },
  {
    name: 'Docker',
    desc: 'Fast, disk space efficient package manager',
    link: 'https://pnpm.io/',
    img: '/logos/docker.svg',
  },
];

export const other = [
  {
    name: 'Bun',
    desc: 'Bun is a fast all-in-one JavaScript runtime and toolkit designed for speed, providing a bundler, transpiler, and package manager with significantly improved performance.',
    link: 'https://bun.sh',
    img: '/logos/bun.svg',
  },
  {
    name: 'Pnpm',
    desc: 'Fast, disk space efficient package manager',
    link: 'https://pnpm.io/',
    img: '/logos/pnpm.svg',
  },
  {
    name: 'Turbo repo',
    desc: 'Fast, disk space efficient package manager',
    link: 'https://pnpm.io/',
    img: '/logos/turborepo.svg',
  },
  {
    name: 'Ubuntu(Linux)',
    desc: "Ubuntu is a user-friendly Linux distribution recognized for its stability and security. It's widely used for desktop and server applications, featuring a customizable environment and extensive package support.",
    link: 'https://ubuntu.com/',
    img: '/logos/ubuntu-4.svg',
  },
];

export const projects = [
  {
    name: 'Taku',
    slug: 'taku',
    desc: 'Taku is the local-first productivity and time tracking app built for makers, founders, and focused creators. Track tasks, log deep work, and hit weekly goals—all without accounts, cloud sync, or distractions. Everything runs offline, in your browser, with fast UX and full data ownership.',
    longDescription: '',
    liveLink: 'https://taku-nu.vercel.app',
    githubLink: 'https://github.com/adityaj07/taku',
    coverImg: '/projects/project-taku.png',
    imgs: [],
    screenshots: ['/projects/ss-taku-1.png'],
    implementation: '',
    features: [
      {
        title: '🧠 Local-first architecture',
        description:
          'All data is stored in the browser using IndexedDB. Your workspace stays private and fully offline.',
      },
      {
        title: '✅ Task-based time tracking',
        description: 'Start/stop timers on tasks or log time manually.',
      },
      {
        title: '🧱 Kanban + List Views',
        description: 'View tasks in a drag-and-drop board or structured list.',
      },
    ],
    timeline: 'June 2025 - Present',
    tech: [
      '/logos/react-2.svg',
      '/logos/next-js-white.svg',
      '/logos/tailwind-css-2.svg',
      '/logos/ts-logo-128.svg',
      '/logos/zod.svg',
      '/logos/zustand.svg',
      '/logos/shadcn.jpeg',
      '/logos/dexie.png',
      '/logos/framer-motion.svg',
    ],
  },
  {
    name: 'Uplog',
    slug: 'uplog',
    desc: 'Uplog is the modern changelog manager designed for SaaS founders and indie devs. Capture every feature release, bug fix, and improvement—publish them on a beautifully designed public page.',
    longDescription: '',
    liveLink: 'https://uplog.vercel.app',
    githubLink: 'https://github.com/adityaj07/uplog',
    coverImg: '/projects/project-uplog.png',
    imgs: [],
    screenshots: [],
    implementation: '',
    features: [],
    timeline: 'June 2025 - Present',
    tech: [
      '/logos/react-2.svg',
      '/logos/next-js-white.svg',
      '/logos/tailwind-css-2.svg',
      '/logos/ts-logo-128.svg',
      '/logos/zod.svg',
      '/logos/nodejs-1.svg',
      '/logos/expressjs-109.svg',
      '/logos/shadcn.jpeg',
      '/logos/prisma-white.svg',
      '/logos/postgresql.svg',
    ],
  },
  {
    name: 'Nebula Forge',
    slug: 'nebula-forge',
    desc: 'A clean and modern landing page made with Nextjs, Tailwind CSS, shadcn, framer motion and a pinch of amazing design.',
    longDescription: '',
    liveLink: 'https://nebula-forge.vercel.app',
    githubLink: 'https://github.com/adityaj07/nebai-landing',
    coverImg: '/projects/project-nebula.png',
    imgs: [],
    screenshots: [],
    implementation: '',
    features: [],
    timeline: 'August 2025',
    tech: [
      '/logos/react-2.svg',
      '/logos/next-js-white.svg',
      '/logos/tailwind-css-2.svg',
      '/logos/ts-logo-128.svg',
      '/logos/shadcn.jpeg',
      '/logos/framer-motion.svg',
    ],
  },

  {
    name: 'FlowPay',
    slug: 'flowpay',
    desc: 'A Paytm-inspired payment platform facilitating user sign-up, seamless peer-to-peer transactions, and efficient user search functionalities for easy money transfers.',
    longDescription: '',
    liveLink: 'https://flow-pay.vercel.app',
    githubLink: 'https://github.com/adityaj07/flowpay',
    coverImg: '/projects/project-flowpay.jpg',
    imgs: [],
    screenshots: [],
    implementation: '',
    features: [],
    timeline: '',
    tech: [
      '/logos/react-2.svg',
      '/logos/tailwind-css-2.svg',
      '/logos/ts-logo-128.svg',
      '/logos/zod.svg',
      '/logos/nodejs-1.svg',
      '/logos/expressjs-109.svg',
      '/logos/mongodb-icon-2.svg',
    ],
  },
  {
    name: 'My Portfolio',
    slug: 'my-portfolio',
    desc: 'The website you are currently on.',
    longDescription: '',
    liveLink: 'https://adityaj07-portfolio.vercel.app',
    githubLink: 'https://github.com/adityaj07/myPorfolio',
    coverImg: '/projects/project-portfolio.png',
    imgs: [],
    screenshots: [],
    implementation: '',
    features: [],
    timeline: '',
    tech: ['/logos/nextjs-13.svg', '/logos/tailwind-css-2.svg', '/logos/ts-logo-128.svg'],
  },
  {
    name: 'Healthsynx',
    slug: 'healthsynx',
    desc: 'HealthSynx is an innovative health and fitness tracker web application that empowers users to lead healthier lives. With clean and sleek design, goal setting, HealthSynx provides comprehensive insights and tracking capabilities.',
    longDescription: '',
    liveLink: 'https://healthsynxx.vercel.app',
    githubLink: 'https://github.com/adityaj07/healthsynx',
    coverImg: '/projects/project-healthsynx.png',
    imgs: [],
    screenshots: [],
    implementation: '',
    features: [],
    timeline: '',
    tech: [
      '/logos/react-2.svg',
      '/logos/tailwind-css-2.svg',
      '/logos/nodejs-1.svg',
      '/logos/expressjs-109.svg',
      '/logos/mongodb-icon-2.svg',
    ],
  },
  {
    name: 'Databiz Landing Page',
    slug: 'databiz-landing-page',
    desc: 'dataBiz is a website landing page built with React and Tailwind Css. It also uses react-icons and react-typed libraries.',
    longDescription: '',
    liveLink: 'https://databiz.netlify.app/',
    githubLink: 'https://github.com/adityaj07/dataBiz',
    coverImg: '/projects/project-databiz.png',
    imgs: [],
    screenshots: [],
    implementation: '',
    features: [],
    timeline: '',
    tech: ['/logos/react-2.svg', '/logos/tailwind-css-2.svg'],
  },
  {
    name: 'Ecolife',
    slug: 'ecolife',
    desc: 'EcoLife is a sustainable living website that I built as a project while learning Astro and as a part of my college project.',
    longDescription: '',
    liveLink: 'https://ecoolife.netlify.app/',
    githubLink: 'https://github.com/adityaj07/EcoLife',
    coverImg: '/projects/project-ecolife.png',
    imgs: [],
    screenshots: [],
    implementation: '',
    features: [],
    timeline: '',
    tech: ['/logos/astro.svg', '/logos/tailwind-css-2.svg'],
  },
  {
    name: 'Lofiflow',
    slug: 'lofiflow',
    desc: 'LofiFlow is a webapp where you can listen to lofi music while you code.',
    longDescription: '',
    liveLink: 'https://lofiflow.netlify.app/',
    githubLink: '',
    coverImg: '/projects/project-lofiflow.png',
    imgs: [],
    screenshots: [],
    implementation: '',
    features: [],
    timeline: '',
    tech: ['/logos/logo-javascript.svg', '/logos/tailwind-css-2.svg'],
  },
  {
    name: 'Working on more ideas.🤓',
    slug: 'working-on-more-ideas',
    desc: 'If you have any idea or want to get one built, reach out me.👀',
    longDescription: '',
    liveLink: '',
    githubLink: '',
    coverImg: '/projects/project-coming-soon.png',
    imgs: [],
    screenshots: [],
    implementation: '',
    features: [],
    timeline: '',
    tech: [],
  },
];

export const experiences = [
  {
    title: 'Full Stack Developer',
    company: 'STPL',
    location: 'Remote • India',
    duration: 'October 2025 - March 2026',
    description: [
      'Built and owned 3 production React Native and React (Next.js) applications, including an app serving 1,500+ users, delivering scalable cross-platform experiences.',
      'Developed and deployed backend APIs on AWS EC2, used S3 for media management, and integrated Razorpay (payments), Google Maps, Firebase Cloud Messaging, and third-party KYC services.',
    ],
    skills: [
      'React Native',
      'React',
      'Next.js',
      'TypeScript',
      'Tailwind CSS',
      'Nativewind',
      'Node.js',
      'Express.js',
      'AWS EC2',
      'AWS S3',
      'MongoDB',
      'Razorpay',
      'Google Maps API',
      'Firebase Cloud Messaging',
      'Socket.io',
    ],
    logo: '/logos/stpl.png',
  },
  {
    title: 'Software Development Engineer Intern',
    company: 'Engaze',
    location: 'Mumbai, India',
    duration: 'August 2024 - February 2025',
    description: [
      'Worked on the core production application of an early-stage startup, developing and shipping end-to-end features such as Blogs and Reels.',
      'Built a complementary full-stack platform from scratch, handling frontend development, backend API design, and fixing production issues across systems.',
    ],
    skills: [
      'React',
      'Next.js',
      'TypeScript',
      'Node.js',
      'Express.js',
      'Prisma',
      'PostgreSQL',
      'Tailwind CSS',
    ],
    logo: '/logos/engaze.svg',
  },
];

export const freelanceProjects = [
  {
    name: 'Momoshu',
    description:
      'Built and deployed a full-stack food ordering platform (mobile app + admin dashboard + POS system) handling 800+ daily orders, with location-based outlet auto-selection, Razorpay payments, Google Maps integration, and AWS-backed infrastructure.',
    tech: [
      'React Native',
      'React (Vite)',
      'Node.js',
      'Express.js',
      'MongoDB',
      'AWS EC2',
      'AWS S3',
      'Zustand',
      'Razorpay',
      'Google Maps API',
    ],
    duration: 'Feb. 2026 - Mar. 2026',
  },
  // Add more here later
];
